---
driver:
  name: vagrant
  provision: true
  vagrantfiles:
    - .kitchen.provision.rb

provisioner:
  name: chef_zero
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-16.04

suites:
  - name: accounts
    run_list:
      - recipe[accounts::default]
  - name: apache
    run_list:
      - recipe[apache::default]
  - name: apache-ssl
    run_list:
      - recipe[apache::ssl]
  - name: apt
    run_list:
      - recipe[apt::default]
  - name: bind
    run_list:
      - recipe[bind::default]
  - name: forum
    run_list:
      - recipe[accounts::default]
      - role[forum]
  - name: munin
    run_list:
      - recipe[munin::default]
  - name: munin-server
    run_list:
      - recipe[munin::server]
  - name: mysql
    run_list:
      - recipe[mysql::default]
  - name: networking
    run_list:
      - recipe[networking::default]
  - name: tools
    run_list:
      - recipe[tools::default]
