---
driver:
  name: dokken
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken
  data_bags_path: test/data_bags

verifier:
  root_path: /opt/verifier

platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y

suites:
  - name: accounts
    run_list:
      - recipe[accounts::default]
  - name: apache
    run_list:
      - recipe[apache::default]
  - name: apt
    run_list:
      - recipe[apt::default]
  - name: bind
    run_list:
      - recipe[bind::default]
    attributes:
      bind:
        clients: none
  - name: blogs
    run_list:
      - recipe[accounts::default]
      - recipe[blogs::default]
  - name: clamav
    run_list:
      - recipe[clamav::default]
  - name: devices
    run_list:
      - recipe[devices::default]
  - name: dhcpd
    run_list:
      - recipe[dhcpd::default]
    attributes:
      dhcpd:
        first_address: 172.18.100.1
        last_address: 172.18.100.254
      networking:
        interfaces:
          test:
            interface: eth0
            role: internal
            address: 172.18.0.2
            prefix: 16
            gateway: 172.18.0.1
        roles:
          external:
            zone: test
  - name: dmca
    run_list:
      - recipe[dmca::default]
    attributes:
      apache:
        mpm: prefork
  - name: donate
    run_list:
      - recipe[accounts::default]
      - role[donate]
    attributes:
      apache:
        mpm: prefork
  - name: exim
    run_list:
      - recipe[exim::default]
  - name: fail2ban
    run_list:
      - recipe[fail2ban::default]
  - name: forum
    run_list:
      - recipe[accounts::default]
      - role[forum]
  - name: letsencrypt
    run_list:
      - recipe[accounts::default]
      - recipe[apt::default]
      - role[letsencrypt]
    attributes:
      apt:
        sources:
          - openstreetmap
  - name: memcached
    run_list:
      - recipe[munin::default]
      - recipe[memcached::default]
  - name: munin
    run_list:
      - recipe[munin::default]
  - name: munin-server
    run_list:
      - recipe[munin::server]
  - name: mysql
    run_list:
      - recipe[mysql::default]
  - name: networking
    run_list:
      - recipe[networking::default]
  - name: nginx
    run_list:
      - recipe[munin::default]
      - recipe[nginx::default]
    attributes:
      networking:
        nameservers:
          - 127.0.0.1
  - name: nodejs
    run_list:
      - recipe[nodejs::default]
  - name: ntp
    run_list:
      - recipe[ntp::default]
  - name: openssh
    run_list:
      - recipe[openssh::default]
  - name: otrs
    run_list:
      - recipe[accounts::default]
      - recipe[chef::default]
      - role[otrs]
  - name: python
    run_list:
      - recipe[python::default]
  - name: spamassassin
    run_list:
      - recipe[spamassassin::default]
  - name: tools
    run_list:
      - recipe[tools::default]
