---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: apt
    run_list:
      - recipe[apt::default]
  - name: munin
    run_list:
      - recipe[munin::default]
  - name: networking
    run_list:
      - recipe[networking::default]
  - name: tools
    run_list:
      - recipe[tools::default]
