inherit_from: .rubocop_todo.yml

Style/AlignParameters:
  Exclude:
    - '**/metadata.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
