inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  Exclude:
    - '**/metadata.rb'

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Style/FileName:
  Exclude:
    - 'cookbooks/trac/files/default/trac-authenticate'
    - 'cookbooks/planet/files/default/replication-bin/replicate-changesets'
    - 'cookbooks/*/templates/*/*.erb'
    - 'hooks/*'
    - 'roles/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
