inherit_from: .rubocop_todo.yml

Style/AlignParameters:
  Exclude:
    - '**/metadata.rb'

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FileName:
  Exclude:
    - 'cookbooks/trac/files/default/trac-authenticate'
    - 'cookbooks/planet/files/default/replication-bin/replicate-changesets'
    - 'cookbooks/*/templates/*/*.erb'
    - 'hooks/*'
    - 'roles/*.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
